### ISSUE TITLE
micro micro

### ISSUE THREAD

**Issue by zaoqi-unsafe** [fisherdj/miniAdapton#3]
Racket
https://github.com/zaoqi/zKanren/blob/master/memorize.rkt 
```racket
;;  zKanren: MicroKanren with Constraints and noto
;;  Copyright (C) 2017  Zaoqi

;;  This program is free software: you can redistribute it and/or modify
;;  it under the terms of the GNU Affero General Public License as published
;;  by the Free Software Foundation, either version 3 of the License, or
;;  (at your option) any later version.

;;  This program is distributed in the hope that it will be useful,
;;  but WITHOUT ANY WARRANTY; without even the implied warranty of
;;  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;;  GNU Affero General Public License for more details.

;;  You should have received a copy of the GNU Affero General Public License
;;  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#lang racket
(provide memorize)

#| (Any ... → a) → (Any ... → a) |#
(define (memorize f)
  (let ([m (make-weak-hash)])
    (λ args (hash-ref m args (λ ()
                               (let ([v (apply f args)])
                                 (hash-set! m args v)
v))))))
```
Write a faster `equal?`

**Comment by fisherdj** [comment]
Could you describe your issue in more detail?

Are you suggesting a shorter/faster implementation? This particular implementation won't fit this particular project, since it requires hash tables, which aren't part of standard Scheme pre-R6RS.

Are you confused about about how a faster variant of `equal?` would improve such an implementation? It would improve the implementation because key-value stores (including hash tables) ultimately have to check `equal?` sometimes. The problem's worse for a hash table implementation, since the cost of hashing is ultimately the same as the worst case for performing `equal?`. Since the equality implementation is tied to the hash function, it also tends to create a lower bound for the function's cost. There is a trick to get around this, though: use a memoized variant of `cons` (hash-consing) to construct a list of arguments which are `equal?` iff they are `eq?`. This lets you use an `eq?` key-value store instead of an `equal?` key-value store, which makes both hashing and comparison O(1).

For now, I'm closing the issue until I know what you're asking better.
